import type { Metadata } from "next";
import LegalDocument from "@/components/LegalDocument";
import { confidentialityWarning, contactHref, deletionHref, siteConfig } from "@/lib/site-config";

export const metadata: Metadata = {
  title: `Privacy Notice | ${siteConfig.applicationName}`,
  description: "How account, engineering, technical and feedback data are processed during the beta, and how to exercise your privacy rights.",
};

export default function PrivacyPage() {
  return <LegalDocument title="Privacy Notice">
    <p>{siteConfig.operatorName}, registered in {siteConfig.operatorCountry} under enterprise number {siteConfig.enterpriseNumber}, operates the {siteConfig.applicationName} and is the controller responsible for the personal data described in this notice.</p>
    <p>Contact: <a href={contactHref}>{siteConfig.contactEmail}</a>.</p>
    <h2>1. Scope</h2>
    <p>This notice applies to the private and public beta of {siteConfig.applicationName}. It covers account, project, calculation and feedback-related processing.</p>
    <h2>2. Data collected</h2>
    <ul>
      <li>Account email, authentication identifiers and information needed to manage sign-in.</li>
      <li>Project and scenario names, descriptions, engineering inputs, saved calculation configurations and results.</li>
      <li>Support and feedback correspondence you voluntarily submit.</li>
      <li>Essential technical and security information, such as request timestamps, IP-related logs, browser/device information and error logs where generated by hosting providers.</li>
      <li>Authentication cookies or browser storage necessary for sign-in, and functional workspace-selection preferences.</li>
    </ul>
    <h2>3. Engineering-data guidance</h2>
    <p className="rounded-lg border border-teal-200 bg-teal-50 p-4 text-teal-900">{confidentialityWarning} Anonymise project labels and engineering descriptions during the beta.</p>
    <h2>4. Purposes</h2>
    <p>We process data to create and manage accounts, authenticate users, operate calculations, save and reopen projects and scenarios, and generate requested reports. We also process relevant information to maintain security, diagnose failures, prevent misuse, respond to support, privacy and feedback requests, and improve the beta service.</p>
    <h2>5. Legal bases</h2>
    <p>Depending on the purpose, processing relies on performance of the requested beta service or steps taken at your request; legitimate interests in operating, securing, troubleshooting and improving the service, balanced against your rights; or compliance with legal obligations where applicable. Consent would be sought for genuinely optional processing introduced later where required. Acknowledging this notice is not consent to all processing.</p>
    <h2>6. Service providers</h2>
    <ul>
      <li>Supabase: authentication and database services.</li>
      <li>Vercel: frontend hosting and delivery.</li>
      <li>Render: backend/API hosting.</li>
      <li>One.com: domain email services.</li>
      <li>Tally: voluntary-feedback form services. If you choose to submit the form, Tally processes the information you provide.</li>
    </ul>
    <p>These providers process data under their own contractual and security arrangements. Engineering requests go to the backend/API; saved project and scenario data are associated with the authenticated account. Requested reports are generated by the backend and downloaded through the application.</p>
    <h2>7. International transfers</h2>
    <p>Some providers may process data outside your country or the European Economic Area. Applicable contractual or legal transfer safeguards are relied upon where required. This notice does not guarantee a specific hosting region or data location.</p>
    <h2>8. Retention</h2>
    <ul>
      <li>Account and project data are retained while the account is active.</li>
      <li>Deleted-account data are deleted or anonymised within 30 days, subject to backups, security requirements and legal obligations.</li>
      <li>Support and feedback correspondence is retained for up to 12 months.</li>
      <li>Security/server logs follow the relevant provider’s operational retention policy, unless longer retention is needed for security or legal reasons.</li>
    </ul>
    <h2>9. Your rights</h2>
    <p>Subject to applicable conditions, you may request access, correction, deletion, restriction, or portability of your personal data, and may object to processing. Where processing is based on consent, you may withdraw it without affecting the lawfulness of earlier processing. Send privacy requests to <a href={contactHref}>{siteConfig.contactEmail}</a>.</p>
    <p>You also have the right to complain to the <a href="https://www.dataprotectionauthority.be/citizen">Belgian Data Protection Authority</a>.</p>
    <h2>10. Account deletion</h2>
    <p>There is currently no self-service account-deletion feature. Email <a href={deletionHref}>{siteConfig.contactEmail}</a> with the subject “Account deletion request”. We may need to verify that you control the account before acting on the request.</p>
    <h2>11. Security</h2>
    <p>Reasonable technical and organisational safeguards are used to protect data, including authentication and account-based access controls. No internet service is risk-free.</p>
    <h2>12. Cookies and browser storage</h2>
    <p>The application uses necessary authentication/session cookies or storage and a functional workspace preference to restore your selected workspace. No non-essential analytics, advertising cookies or tracking pixels are currently integrated in the application. No optional tracking consent banner is used. Hosting providers may generate operational and security logs as described above.</p>
    <h2>13. Children and changes</h2>
    <p>The beta is intended for professional adult users and is not directed at children. This notice may be updated as the service develops; its effective or last-updated date will change when it is revised.</p>
    <h2>14. Contact</h2>
    <p>{siteConfig.operatorName}<br />Belgian enterprise number {siteConfig.enterpriseNumber}<br />{siteConfig.operatorCountry}<br /><a href={contactHref}>{siteConfig.contactEmail}</a></p>
  </LegalDocument>;
}
